### ISSUE TITLE
Preventing Web Notif

### ISSUE THREAD

**Issue by PrinceBunBun981** [dclstn/better-snapchat#124]
Would it be possible to prevent the laptop icon from showing for other people when viewing chats on Snapchat Web?

**Comment by dclstn** [comment]
Hmm, possibly it would require intercepting the socket requests. I'd need to look more into it and get back to you

**Comment by dclstn** [comment]
v1.2.0 adds a new settings to remove your bitmoji entirely, however I know that's not what's requested here, still looking into a way to send as mobile.

**Comment by dclstn** [comment]
Hi, bumping this to let you know I have a solution to this, https://github.com/dclstn/better-snapchat/commit/b246bb2fdc721a7c8e749ad7c0af9dc5c5f044e2

and will be available next patch.

**Comment by PrinceBunBun981** [comment]
Awesome! Thanks
