### ISSUE TITLE
"You are no longer present."

### ISSUE THREAD

**Issue by actorpus** [dclstn/better-snapchat#141]
![image](https://github.com/dclstn/better-snapchat/assets/47696241/f529ba9d-1713-4c7f-a82a-cd3ef6d4ab68)

Would it be possible to add a toggle that removes the check if the window is currently being focused? 
Thanks.

**Comment by dclstn** [comment]
I've now added a setting for this, which should appear when the chrome extension gets approved.

**Comment by dclstn** [comment]
Extension has been updated.
