### ISSUE TITLE
Where is download button? has it been updated? or removed?

### ISSUE THREAD

**Issue by thankyou1369** [dclstn/better-snapchat#167]
This app is amazing thank you so much,recently i have discovered there isnt a download button anymore ? everything else working fine.

**Comment by dclstn** [comment]
Snapchat's new UI broke the button, I've replaced the setting with the ability to right-click and save image. Like you do for any other image online.

This functionality should also work for videos and audio snippets.

**Comment by dclstn** [comment]
Extension has been updated, and should let you right-click and save images/videos
