### ISSUE TITLE
Always Present behaviour

### ISSUE THREAD

**Issue by HenryBaby** [dclstn/better-snapchat#205]
Would it be possible to have the always present module behave as it did a couple of version back? Right now, the always present module also acts as having read the latest sent messages (which I suppose is normal behavior), however in a couple of version back this was not the case, the always present functionality only altered the "not present" splash screen.

So maybe another option that only disables that screen but doesn't act as always present?

Edit: I believe the version that had this behavior was [1.1.0](https://github.com/dclstn/better-snapchat/releases/tag/v1.1.0)

**Comment by dclstn** [comment]
I didn't realise the previous itteration had this side-effect, I'll look into adding a new setting for this. Thanks

**Comment by dclstn** [comment]
Added under Chat Settings as of v1.2.5

**Comment by HenryBaby** [comment]
Great implementation! Thank you so much!
