### ISSUE TITLE
Showing user Image in push notification along with username

### ISSUE THREAD

**Issue by MirzaHasnat** [dclstn/better-snapchat#257]
Absolutely, it's fantastic to see the push notifications in the extension!, but is there any way we can show bitmoji in push notification along with username?

Here's what I have discovered
Snapchat provides a URL to fetch the user's QR code, which includes a separate data URI for Bitmoji when inspected. This data URI could potentially be utilized to display Bitmoji in push notifications.

The URL to fetch the QR code is:
https://app.snapchat.com/web/deeplink/snapcode?username=<username>&type=SVG

You can replace <username> with the actual username of the user you want to fetch the QR code for. 

Thanks

**Comment by dclstn** [comment]
This is available on v1.3.2

https://github.com/dclstn/better-snapchat/commit/bc8f7dcf445d09dda5329b382d8b1c8188cc03e9
