### ISSUE TITLE
Configurable opened chat/half-swipe notification close delay

### ISSUE THREAD

**Issue by IsaacHatton** [dclstn/better-snapchat#259]
As referenced here, https://discord.com/channels/1217438562107002940/1217438562107002943/1240031061841285251

Some use cases require the notification to remain in the notification center for longer than 5000ms, so making this configurable would be useful.

**Comment by MirzaHasnat** [comment]
Yup, that would be so helpfull, can we make it to soemthing like "dont close notification until the user click on close"

**Comment by Robloxfan2233335** [comment]
I would love a feature like that. It's taking Snap forever to implement a view snaps feature for the web, without such a feature, Snapchat for Web is pointless.

**Comment by dclstn** [comment]
This timeout has now been removed, and will remain in your notification centre

https://github.com/dclstn/better-snapchat/commit/bc8f7dcf445d09dda5329b382d8b1c8188cc03e9
