### ISSUE TITLE
In "opened chat" notification or "peeked" notification, specify which chat has been opened, such as a group chat

### ISSUE THREAD

**Issue by Cuailo** [dclstn/better-snapchat#262]
At the moment when a chat is opened by someone it says, "(name) has opened your chat" and it still says this for group chats, this is the same case for when someone has half swiped that chat. Would it be possible to add the name of the group chat when someone opens it like, "(name) has opened/peeked (chat name)"

**Comment by dclstn** [comment]
This is available on v1.3.2

https://github.com/dclstn/better-snapchat/commit/bc8f7dcf445d09dda5329b382d8b1c8188cc03e9
