### ISSUE TITLE
It does not work on chrome & chromium

### ISSUE THREAD

**Issue by ney-web** [dclstn/better-snapchat#40]
No icon is displayed after installing the extension

Someone can help me to use it?

**Comment by dclstn** [comment]
I'm unable to reproduce it, can you open the console `CTRL + J` and see if there's an error on page-load?

**Comment by ney-web** [comment]
![image](https://user-images.githubusercontent.com/83525383/204537954-0eb24c59-3638-44d4-b413-b209b3783092.png)
 this ?

**Comment by ney-web** [comment]
bro??

**Comment by dclstn** [comment]
I cannot replicate this issue you're having, have you tried reinstalling the extension? When installed an icon should appear next to a recipient's username, above your messages.

**Comment by ney-web** [comment]
What browser you use?

**Comment by dclstn** [comment]
The extension was developed using chrome, I'll look more into this however.

**Comment by ney-web** [comment]
I also use chrome but I don't understand why it doesn't work
