### ISSUE TITLE
The feature *Prevent Typing Notification* is not working.

### ISSUE THREAD

**Issue by kaushik-rishi** [dclstn/better-snapchat#66]
**Browser:** Google Chrome

The extension is not able to block the **typing notifications**

**My Research: **
- The extension seems like it's blocking the HTTP requests on this `https://web.snapchat.com/messagingcoreservice.MessagingCoreService/SendTypingNotification` endpoint.
- It's successfuly able to block those requests
- But i feel, the typing events are also being streamed via the estabilished web socket connection

That is the reason which the typing events are not able to be prevented.

**Comment by dclstn** [comment]
I'm aware, I've put extensive time trying to intercept these socket requests, however to no avail. Blocking "SendTypingNotifcation" prevents mobile devices from receiving push notifications.

**Comment by dclstn** [comment]
This feature simply blocks push notifications, and not in-app notifications.

**Comment by kaushik-rishi** [comment]
Makes sense @dclstn
